add check to ci

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -26,6 +26,30 @@ jobs:
         run: |
           python manage.py test --settings=la_mulerie_training.settings.prod
 
+      - name: Check secrets
+        run: |
+          if [ -z "${{ secrets.SERVER_HOST }}" ]; then
+            echo "SERVER_HOST is missing!"
+            exit 1
+          else
+            echo "SERVER_HOST is set"
+          fi
+
+          if [ -z "${{ secrets.SERVER_USER }}" ]; then
+            echo "SERVER_USER is missing!"
+            exit 1
+          else
+            echo "SERVER_USER is set"
+          fi
+
+          if [ -z "${{ secrets.SERVER_SSH_KEY }}" ]; then
+            echo "SERVER_SSH_KEY is missing!"
+            exit 1
+          else
+            echo "SERVER_SSH_KEY is set"
+          fi
+
+
       - name: Deploy to VPS via SSH
         if: success()  # ne se lance que si les tests passent
         uses: appleboy/ssh-action@v1.0.0
@@ -35,14 +59,7 @@ jobs:
           key: ${{ secrets.SERVER_SSH_KEY }}
           script: |
             cd /var/www/la_mulerie_training
-            for s in SERVER_HOST SERVER_USER SERVER_SSH_KEY; do
-              if [ -z "${{ secrets[$s] }}" ]; then
-                echo "$s missing"
-                exit 1
-              else
-                echo "$s is set"
-              fi
-            done
+          
             chmod +x deploy.sh
             ./deploy.sh
  
